theme: minima
title: Your awesome title
author: enricko7
email: mr.erikpetersen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Life is actually pretty boring. But here's what I've managed to do.

# social links
twitter_username: Erkisme # DO NOT include the @ character, or else the build will fail!
github_username:  enricko7 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

